# Site settings
author: Shishiri Nganyone
title: Why I Decided to Study Software Engineering
header-img: img/home-bg.png
email: snganyone1@gmail.com
copyright_name: Shishiri Nganyone
description: > # this means to ignore newlines until "baseurl:"
  First Mile
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  snganyone

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
